### ISSUE TITLE
Config file isn't generated at ".minecraft/config/stretchy-leash.properties"

### ISSUE THREAD

**Issue by nightbrd** [Estecka/mc-Stretchy-Leash#3]
The expected behavior is for a config file to be generated on the config folder for the client or server, but doesn't. I assume this is a problem with the mod, possibly?

**Comment by Estecka** [comment]
That's actually intended for this mod, although this behaviour is more of an experiment than anything.
The mod still attempts to find and read from the config file, but will not create one on startup. If missing, it will just use the built-in defaults. On client, the full config file should still be created after making any changes in the config screen.

**Comment by nightbrd** [comment]
Oh alright, I just thought it wouldn't be intended as most of all the other mods I've seen do create a config file at launch nonetheless, without needing any mod that lets you change mod configs. 
In the case of if you're running it in a server, which is the case here, it would be helpful, as you'd only need to go into the server files and tweak around the settings as needed, without having to make a new text file, rename it, and input all the separate editable settings of the mod yourself. But I see if it is done as an experiment.

**Comment by Estecka** [comment]
Agreed. I guess this also ties in with the complete inability to edit the config at runtime on servers.

**Comment by Estecka** [comment]
I'll keep trying out this behaviour a while longer, but now it's possible for servers to change the config at runtime using commands. This should be less of an issue.
